package com.landasoft.gshealthycode.mapper;

import com.landasoft.gshealthycode.pojo.TArea;
import com.landasoft.gshealthycode.pojo.TAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbggenerated Wed Apr 29 09:49:06 CST 2020
     */
    int countByExample(TAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbggenerated Wed Apr 29 09:49:06 CST 2020
     */
    int deleteByExample(TAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbggenerated Wed Apr 29 09:49:06 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbggenerated Wed Apr 29 09:49:06 CST 2020
     */
    int insert(TArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbggenerated Wed Apr 29 09:49:06 CST 2020
     */
    int insertSelective(TArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbggenerated Wed Apr 29 09:49:06 CST 2020
     */
    List<TArea> selectByExample(TAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbggenerated Wed Apr 29 09:49:06 CST 2020
     */
    TArea selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbggenerated Wed Apr 29 09:49:06 CST 2020
     */
    int updateByExampleSelective(@Param("record") TArea record, @Param("example") TAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbggenerated Wed Apr 29 09:49:06 CST 2020
     */
    int updateByExample(@Param("record") TArea record, @Param("example") TAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbggenerated Wed Apr 29 09:49:06 CST 2020
     */
    int updateByPrimaryKeySelective(TArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbggenerated Wed Apr 29 09:49:06 CST 2020
     */
    int updateByPrimaryKey(TArea record);
}