package com.landasoft.gshealthycode.mapper;

import com.landasoft.gshealthycode.pojo.TStatistics;
import com.landasoft.gshealthycode.pojo.TStatisticsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    int countByExample(TStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    int deleteByExample(TStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    int insert(TStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    int insertSelective(TStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    List<TStatistics> selectByExample(TStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    TStatistics selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") TStatistics record, @Param("example") TStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    int updateByExample(@Param("record") TStatistics record, @Param("example") TStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    int updateByPrimaryKeySelective(TStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    int updateByPrimaryKey(TStatistics record);
}