package com.landasoft.gshealthycode.mapper;

import com.landasoft.gshealthycode.pojo.TVerificationCode;
import com.landasoft.gshealthycode.pojo.TVerificationCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TVerificationCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_verification_code
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    int countByExample(TVerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_verification_code
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    int deleteByExample(TVerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_verification_code
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_verification_code
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    int insert(TVerificationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_verification_code
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    int insertSelective(TVerificationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_verification_code
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    List<TVerificationCode> selectByExample(TVerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_verification_code
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    TVerificationCode selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_verification_code
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") TVerificationCode record, @Param("example") TVerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_verification_code
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    int updateByExample(@Param("record") TVerificationCode record, @Param("example") TVerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_verification_code
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    int updateByPrimaryKeySelective(TVerificationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_verification_code
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    int updateByPrimaryKey(TVerificationCode record);
}