package com.landasoft.gshealthycode.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TStatisticsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public TStatisticsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNull() {
            addCriterion("id_card is null");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNotNull() {
            addCriterion("id_card is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardEqualTo(String value) {
            addCriterion("id_card =", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotEqualTo(String value) {
            addCriterion("id_card <>", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThan(String value) {
            addCriterion("id_card >", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("id_card >=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThan(String value) {
            addCriterion("id_card <", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThanOrEqualTo(String value) {
            addCriterion("id_card <=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLike(String value) {
            addCriterion("id_card like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotLike(String value) {
            addCriterion("id_card not like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardIn(List<String> values) {
            addCriterion("id_card in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotIn(List<String> values) {
            addCriterion("id_card not in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardBetween(String value1, String value2) {
            addCriterion("id_card between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotBetween(String value1, String value2) {
            addCriterion("id_card not between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNull() {
            addCriterion("phone_number is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNotNull() {
            addCriterion("phone_number is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberEqualTo(String value) {
            addCriterion("phone_number =", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotEqualTo(String value) {
            addCriterion("phone_number <>", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThan(String value) {
            addCriterion("phone_number >", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThanOrEqualTo(String value) {
            addCriterion("phone_number >=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThan(String value) {
            addCriterion("phone_number <", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThanOrEqualTo(String value) {
            addCriterion("phone_number <=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLike(String value) {
            addCriterion("phone_number like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotLike(String value) {
            addCriterion("phone_number not like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIn(List<String> values) {
            addCriterion("phone_number in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotIn(List<String> values) {
            addCriterion("phone_number not in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberBetween(String value1, String value2) {
            addCriterion("phone_number between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotBetween(String value1, String value2) {
            addCriterion("phone_number not between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andNumberVerificationCodeIsNull() {
            addCriterion("number_verification_code is null");
            return (Criteria) this;
        }

        public Criteria andNumberVerificationCodeIsNotNull() {
            addCriterion("number_verification_code is not null");
            return (Criteria) this;
        }

        public Criteria andNumberVerificationCodeEqualTo(String value) {
            addCriterion("number_verification_code =", value, "numberVerificationCode");
            return (Criteria) this;
        }

        public Criteria andNumberVerificationCodeNotEqualTo(String value) {
            addCriterion("number_verification_code <>", value, "numberVerificationCode");
            return (Criteria) this;
        }

        public Criteria andNumberVerificationCodeGreaterThan(String value) {
            addCriterion("number_verification_code >", value, "numberVerificationCode");
            return (Criteria) this;
        }

        public Criteria andNumberVerificationCodeGreaterThanOrEqualTo(String value) {
            addCriterion("number_verification_code >=", value, "numberVerificationCode");
            return (Criteria) this;
        }

        public Criteria andNumberVerificationCodeLessThan(String value) {
            addCriterion("number_verification_code <", value, "numberVerificationCode");
            return (Criteria) this;
        }

        public Criteria andNumberVerificationCodeLessThanOrEqualTo(String value) {
            addCriterion("number_verification_code <=", value, "numberVerificationCode");
            return (Criteria) this;
        }

        public Criteria andNumberVerificationCodeLike(String value) {
            addCriterion("number_verification_code like", value, "numberVerificationCode");
            return (Criteria) this;
        }

        public Criteria andNumberVerificationCodeNotLike(String value) {
            addCriterion("number_verification_code not like", value, "numberVerificationCode");
            return (Criteria) this;
        }

        public Criteria andNumberVerificationCodeIn(List<String> values) {
            addCriterion("number_verification_code in", values, "numberVerificationCode");
            return (Criteria) this;
        }

        public Criteria andNumberVerificationCodeNotIn(List<String> values) {
            addCriterion("number_verification_code not in", values, "numberVerificationCode");
            return (Criteria) this;
        }

        public Criteria andNumberVerificationCodeBetween(String value1, String value2) {
            addCriterion("number_verification_code between", value1, value2, "numberVerificationCode");
            return (Criteria) this;
        }

        public Criteria andNumberVerificationCodeNotBetween(String value1, String value2) {
            addCriterion("number_verification_code not between", value1, value2, "numberVerificationCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterIsNull() {
            addCriterion("household_register is null");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterIsNotNull() {
            addCriterion("household_register is not null");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterEqualTo(String value) {
            addCriterion("household_register =", value, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterNotEqualTo(String value) {
            addCriterion("household_register <>", value, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterGreaterThan(String value) {
            addCriterion("household_register >", value, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterGreaterThanOrEqualTo(String value) {
            addCriterion("household_register >=", value, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterLessThan(String value) {
            addCriterion("household_register <", value, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterLessThanOrEqualTo(String value) {
            addCriterion("household_register <=", value, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterLike(String value) {
            addCriterion("household_register like", value, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterNotLike(String value) {
            addCriterion("household_register not like", value, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterIn(List<String> values) {
            addCriterion("household_register in", values, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterNotIn(List<String> values) {
            addCriterion("household_register not in", values, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterBetween(String value1, String value2) {
            addCriterion("household_register between", value1, value2, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterNotBetween(String value1, String value2) {
            addCriterion("household_register not between", value1, value2, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterCodeIsNull() {
            addCriterion("household_register_code is null");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterCodeIsNotNull() {
            addCriterion("household_register_code is not null");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterCodeEqualTo(String value) {
            addCriterion("household_register_code =", value, "householdRegisterCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterCodeNotEqualTo(String value) {
            addCriterion("household_register_code <>", value, "householdRegisterCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterCodeGreaterThan(String value) {
            addCriterion("household_register_code >", value, "householdRegisterCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterCodeGreaterThanOrEqualTo(String value) {
            addCriterion("household_register_code >=", value, "householdRegisterCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterCodeLessThan(String value) {
            addCriterion("household_register_code <", value, "householdRegisterCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterCodeLessThanOrEqualTo(String value) {
            addCriterion("household_register_code <=", value, "householdRegisterCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterCodeLike(String value) {
            addCriterion("household_register_code like", value, "householdRegisterCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterCodeNotLike(String value) {
            addCriterion("household_register_code not like", value, "householdRegisterCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterCodeIn(List<String> values) {
            addCriterion("household_register_code in", values, "householdRegisterCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterCodeNotIn(List<String> values) {
            addCriterion("household_register_code not in", values, "householdRegisterCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterCodeBetween(String value1, String value2) {
            addCriterion("household_register_code between", value1, value2, "householdRegisterCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterCodeNotBetween(String value1, String value2) {
            addCriterion("household_register_code not between", value1, value2, "householdRegisterCode");
            return (Criteria) this;
        }

        public Criteria andIsLeaveGansuIsNull() {
            addCriterion("is_leave_gansu is null");
            return (Criteria) this;
        }

        public Criteria andIsLeaveGansuIsNotNull() {
            addCriterion("is_leave_gansu is not null");
            return (Criteria) this;
        }

        public Criteria andIsLeaveGansuEqualTo(Boolean value) {
            addCriterion("is_leave_gansu =", value, "isLeaveGansu");
            return (Criteria) this;
        }

        public Criteria andIsLeaveGansuNotEqualTo(Boolean value) {
            addCriterion("is_leave_gansu <>", value, "isLeaveGansu");
            return (Criteria) this;
        }

        public Criteria andIsLeaveGansuGreaterThan(Boolean value) {
            addCriterion("is_leave_gansu >", value, "isLeaveGansu");
            return (Criteria) this;
        }

        public Criteria andIsLeaveGansuGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_leave_gansu >=", value, "isLeaveGansu");
            return (Criteria) this;
        }

        public Criteria andIsLeaveGansuLessThan(Boolean value) {
            addCriterion("is_leave_gansu <", value, "isLeaveGansu");
            return (Criteria) this;
        }

        public Criteria andIsLeaveGansuLessThanOrEqualTo(Boolean value) {
            addCriterion("is_leave_gansu <=", value, "isLeaveGansu");
            return (Criteria) this;
        }

        public Criteria andIsLeaveGansuIn(List<Boolean> values) {
            addCriterion("is_leave_gansu in", values, "isLeaveGansu");
            return (Criteria) this;
        }

        public Criteria andIsLeaveGansuNotIn(List<Boolean> values) {
            addCriterion("is_leave_gansu not in", values, "isLeaveGansu");
            return (Criteria) this;
        }

        public Criteria andIsLeaveGansuBetween(Boolean value1, Boolean value2) {
            addCriterion("is_leave_gansu between", value1, value2, "isLeaveGansu");
            return (Criteria) this;
        }

        public Criteria andIsLeaveGansuNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_leave_gansu not between", value1, value2, "isLeaveGansu");
            return (Criteria) this;
        }

        public Criteria andIsFeverIsNull() {
            addCriterion("is_fever is null");
            return (Criteria) this;
        }

        public Criteria andIsFeverIsNotNull() {
            addCriterion("is_fever is not null");
            return (Criteria) this;
        }

        public Criteria andIsFeverEqualTo(Boolean value) {
            addCriterion("is_fever =", value, "isFever");
            return (Criteria) this;
        }

        public Criteria andIsFeverNotEqualTo(Boolean value) {
            addCriterion("is_fever <>", value, "isFever");
            return (Criteria) this;
        }

        public Criteria andIsFeverGreaterThan(Boolean value) {
            addCriterion("is_fever >", value, "isFever");
            return (Criteria) this;
        }

        public Criteria andIsFeverGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_fever >=", value, "isFever");
            return (Criteria) this;
        }

        public Criteria andIsFeverLessThan(Boolean value) {
            addCriterion("is_fever <", value, "isFever");
            return (Criteria) this;
        }

        public Criteria andIsFeverLessThanOrEqualTo(Boolean value) {
            addCriterion("is_fever <=", value, "isFever");
            return (Criteria) this;
        }

        public Criteria andIsFeverIn(List<Boolean> values) {
            addCriterion("is_fever in", values, "isFever");
            return (Criteria) this;
        }

        public Criteria andIsFeverNotIn(List<Boolean> values) {
            addCriterion("is_fever not in", values, "isFever");
            return (Criteria) this;
        }

        public Criteria andIsFeverBetween(Boolean value1, Boolean value2) {
            addCriterion("is_fever between", value1, value2, "isFever");
            return (Criteria) this;
        }

        public Criteria andIsFeverNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_fever not between", value1, value2, "isFever");
            return (Criteria) this;
        }

        public Criteria andCodePathIsNull() {
            addCriterion("code_path is null");
            return (Criteria) this;
        }

        public Criteria andCodePathIsNotNull() {
            addCriterion("code_path is not null");
            return (Criteria) this;
        }

        public Criteria andCodePathEqualTo(String value) {
            addCriterion("code_path =", value, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathNotEqualTo(String value) {
            addCriterion("code_path <>", value, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathGreaterThan(String value) {
            addCriterion("code_path >", value, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathGreaterThanOrEqualTo(String value) {
            addCriterion("code_path >=", value, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathLessThan(String value) {
            addCriterion("code_path <", value, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathLessThanOrEqualTo(String value) {
            addCriterion("code_path <=", value, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathLike(String value) {
            addCriterion("code_path like", value, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathNotLike(String value) {
            addCriterion("code_path not like", value, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathIn(List<String> values) {
            addCriterion("code_path in", values, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathNotIn(List<String> values) {
            addCriterion("code_path not in", values, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathBetween(String value1, String value2) {
            addCriterion("code_path between", value1, value2, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathNotBetween(String value1, String value2) {
            addCriterion("code_path not between", value1, value2, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodeColorIsNull() {
            addCriterion("code_color is null");
            return (Criteria) this;
        }

        public Criteria andCodeColorIsNotNull() {
            addCriterion("code_color is not null");
            return (Criteria) this;
        }

        public Criteria andCodeColorEqualTo(String value) {
            addCriterion("code_color =", value, "codeColor");
            return (Criteria) this;
        }

        public Criteria andCodeColorNotEqualTo(String value) {
            addCriterion("code_color <>", value, "codeColor");
            return (Criteria) this;
        }

        public Criteria andCodeColorGreaterThan(String value) {
            addCriterion("code_color >", value, "codeColor");
            return (Criteria) this;
        }

        public Criteria andCodeColorGreaterThanOrEqualTo(String value) {
            addCriterion("code_color >=", value, "codeColor");
            return (Criteria) this;
        }

        public Criteria andCodeColorLessThan(String value) {
            addCriterion("code_color <", value, "codeColor");
            return (Criteria) this;
        }

        public Criteria andCodeColorLessThanOrEqualTo(String value) {
            addCriterion("code_color <=", value, "codeColor");
            return (Criteria) this;
        }

        public Criteria andCodeColorLike(String value) {
            addCriterion("code_color like", value, "codeColor");
            return (Criteria) this;
        }

        public Criteria andCodeColorNotLike(String value) {
            addCriterion("code_color not like", value, "codeColor");
            return (Criteria) this;
        }

        public Criteria andCodeColorIn(List<String> values) {
            addCriterion("code_color in", values, "codeColor");
            return (Criteria) this;
        }

        public Criteria andCodeColorNotIn(List<String> values) {
            addCriterion("code_color not in", values, "codeColor");
            return (Criteria) this;
        }

        public Criteria andCodeColorBetween(String value1, String value2) {
            addCriterion("code_color between", value1, value2, "codeColor");
            return (Criteria) this;
        }

        public Criteria andCodeColorNotBetween(String value1, String value2) {
            addCriterion("code_color not between", value1, value2, "codeColor");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("created is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("created is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("created =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("created <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("created >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("created >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("created <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("created <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("created in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("created not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("created between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("created not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNull() {
            addCriterion("updated is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNotNull() {
            addCriterion("updated is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedEqualTo(Date value) {
            addCriterion("updated =", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotEqualTo(Date value) {
            addCriterion("updated <>", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThan(Date value) {
            addCriterion("updated >", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("updated >=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThan(Date value) {
            addCriterion("updated <", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("updated <=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedIn(List<Date> values) {
            addCriterion("updated in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotIn(List<Date> values) {
            addCriterion("updated not in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedBetween(Date value1, Date value2) {
            addCriterion("updated between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("updated not between", value1, value2, "updated");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_statistics
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 30 22:28:37 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_statistics
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}