package com.landasoft.gshealthycode.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class TStatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.id
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.name
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.id_card
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.phone_number
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.number_verification_code
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    private String numberVerificationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.household_register
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    private String householdRegister;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.household_register_code
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    private String householdRegisterCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.is_leave_gansu
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    private Boolean isLeaveGansu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.is_fever
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    private Boolean isFever;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.code_path
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    private String codePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.code_color
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    private String codeColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.created
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.updated
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.id
     *
     * @return the value of t_statistics.id
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.id
     *
     * @param id the value for t_statistics.id
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.name
     *
     * @return the value of t_statistics.name
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.name
     *
     * @param name the value for t_statistics.name
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.id_card
     *
     * @return the value of t_statistics.id_card
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.id_card
     *
     * @param idCard the value for t_statistics.id_card
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.phone_number
     *
     * @return the value of t_statistics.phone_number
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.phone_number
     *
     * @param phoneNumber the value for t_statistics.phone_number
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.number_verification_code
     *
     * @return the value of t_statistics.number_verification_code
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public String getNumberVerificationCode() {
        return numberVerificationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.number_verification_code
     *
     * @param numberVerificationCode the value for t_statistics.number_verification_code
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public void setNumberVerificationCode(String numberVerificationCode) {
        this.numberVerificationCode = numberVerificationCode == null ? null : numberVerificationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.household_register
     *
     * @return the value of t_statistics.household_register
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public String getHouseholdRegister() {
        return householdRegister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.household_register
     *
     * @param householdRegister the value for t_statistics.household_register
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public void setHouseholdRegister(String householdRegister) {
        this.householdRegister = householdRegister == null ? null : householdRegister.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.household_register_code
     *
     * @return the value of t_statistics.household_register_code
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public String getHouseholdRegisterCode() {
        return householdRegisterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.household_register_code
     *
     * @param householdRegisterCode the value for t_statistics.household_register_code
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public void setHouseholdRegisterCode(String householdRegisterCode) {
        this.householdRegisterCode = householdRegisterCode == null ? null : householdRegisterCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.is_leave_gansu
     *
     * @return the value of t_statistics.is_leave_gansu
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public Boolean getIsLeaveGansu() {
        return isLeaveGansu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.is_leave_gansu
     *
     * @param isLeaveGansu the value for t_statistics.is_leave_gansu
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public void setIsLeaveGansu(Boolean isLeaveGansu) {
        this.isLeaveGansu = isLeaveGansu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.is_fever
     *
     * @return the value of t_statistics.is_fever
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public Boolean getIsFever() {
        return isFever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.is_fever
     *
     * @param isFever the value for t_statistics.is_fever
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public void setIsFever(Boolean isFever) {
        this.isFever = isFever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.code_path
     *
     * @return the value of t_statistics.code_path
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public String getCodePath() {
        return codePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.code_path
     *
     * @param codePath the value for t_statistics.code_path
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public void setCodePath(String codePath) {
        this.codePath = codePath == null ? null : codePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.code_color
     *
     * @return the value of t_statistics.code_color
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public String getCodeColor() {
        return codeColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.code_color
     *
     * @param codeColor the value for t_statistics.code_color
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public void setCodeColor(String codeColor) {
        this.codeColor = codeColor == null ? null : codeColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.created
     *
     * @return the value of t_statistics.created
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.created
     *
     * @param created the value for t_statistics.created
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.updated
     *
     * @return the value of t_statistics.updated
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.updated
     *
     * @param updated the value for t_statistics.updated
     *
     * @mbggenerated Thu Apr 30 22:28:37 CST 2020
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}