package com.landasoft.gshealthycode.pojo;

import java.util.Date;

public class TVerificationCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_verification_code.id
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_verification_code.name
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_verification_code.phone_number
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_verification_code.verification_code
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    private String verificationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_verification_code.is_verification
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    private Boolean isVerification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_verification_code.created
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_verification_code.updated
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_verification_code.id
     *
     * @return the value of t_verification_code.id
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_verification_code.id
     *
     * @param id the value for t_verification_code.id
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_verification_code.name
     *
     * @return the value of t_verification_code.name
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_verification_code.name
     *
     * @param name the value for t_verification_code.name
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_verification_code.phone_number
     *
     * @return the value of t_verification_code.phone_number
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_verification_code.phone_number
     *
     * @param phoneNumber the value for t_verification_code.phone_number
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_verification_code.verification_code
     *
     * @return the value of t_verification_code.verification_code
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    public String getVerificationCode() {
        return verificationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_verification_code.verification_code
     *
     * @param verificationCode the value for t_verification_code.verification_code
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    public void setVerificationCode(String verificationCode) {
        this.verificationCode = verificationCode == null ? null : verificationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_verification_code.is_verification
     *
     * @return the value of t_verification_code.is_verification
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    public Boolean getIsVerification() {
        return isVerification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_verification_code.is_verification
     *
     * @param isVerification the value for t_verification_code.is_verification
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    public void setIsVerification(Boolean isVerification) {
        this.isVerification = isVerification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_verification_code.created
     *
     * @return the value of t_verification_code.created
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_verification_code.created
     *
     * @param created the value for t_verification_code.created
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_verification_code.updated
     *
     * @return the value of t_verification_code.updated
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_verification_code.updated
     *
     * @param updated the value for t_verification_code.updated
     *
     * @mbggenerated Wed Apr 29 15:58:04 CST 2020
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}